apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: helloworld-v2
  template:
    metadata:
      labels:
        app: helloworld-v2
    spec:
      containers:
      - name: helloworld-v2
        image: <yourACRRegistry.azurecr.io>/helloworld:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: <k8sSecretName>
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-v2
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30304
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: helloworld-v2
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-v2-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: demok8s.example.com
    http:
      paths:
      - path: /v2
        backend:
          serviceName: helloworld-v2
          servicePort: http
