apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-internal-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: helloworld-internal
  template:
    metadata:
      labels:
        app: helloworld-internal
    spec:
      containers:
      - name: helloworld-internal
        image: <yourACRRegistry.azurecr.io>/helloworld:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: <k8sSecretName>
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "services"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30305
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: helloworld-internal
