apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: mongo
spec:
 serviceName: "mongo"
 replicas: 3
 template:
  metadata:
   labels:
    role: mongo
    environment: demo
  spec:
    terminationGracePeriodSeconds: 10
    containers:
    - name: mongo
      image: mongo
      command:
       - mongod
       - "--replSet"
       - rs0
       - "--bind_ip_all"
      ports:
       - containerPort: 27017
      volumeMounts:
       - name: mongo-persistent-storage
         mountPath: /data/db
    - name: mongo-sidecar
      image: cvallance/mongo-k8s-sidecar
      env:
      - name: MONGO_SIDECAR_POD_LABELS
        value: "role=mongo,environment=demo"
 volumeClaimTemplates:
 - metadata:
    name: mongo-persistent-storage
    annotations:
     volume.beta.kubernetes.io/storage-class: "fast"
   spec:
    accessModes: ["ReadWriteOnce"]
    resources:
     requests:
      storage: 25Gi
